services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_ROOT_PASSWORD=password'
      - 'MARIADB_DATABASE=railmetrics'
      - 'MARIADB_PASSWORD=password'
      - 'MARIADB_USER=root'
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  data: